import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:offline_home/adapters/tuya/tuya_codec.dart';

/// Vectors generated by tinytuya itself: sim/tools/gen_tuya_vectors.py.
final vectors = jsonDecode(
  File('test/adapters/tuya/vectors_3x.json').readAsStringSync(),
) as Map<String, Object?>;

Uint8List hex(String s) => Uint8List.fromList([
  for (var i = 0; i < s.length; i += 2)
    int.parse(s.substring(i, i + 2), radix: 16),
]);

String toHex(List<int> b) =>
    b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

void main() {
  final key = vectors['key']! as String;
  final now = DateTime.fromMillisecondsSinceEpoch(
    (vectors['t']! as int) * 1000,
  );

  test('crc32 matches zlib', () {
    expect(crc32(ascii.encode('123456789')), 0xCBF43926);
  });

  test('udp key is md5("yGAdlopoPVldABfn")', () {
    expect(toHex(tuyaUdpKey), (vectors['beacon']! as Map)['udpKey']);
  });

  group('client frames byte-exact vs tinytuya', () {
    for (final v in (vectors['client']! as List).cast<Map<String, Object?>>()) {
      final version = v['version']! as String;
      final cmd = v['command']! as int;
      final devId = v['devId']! as String;
      final device22 = v['sentCommand'] != cmd;
      test(
        'v$version cmd 0x${cmd.toRadixString(16)}${device22 ? ' (device22)' : ''} seq ${v['seq']}',
        () {
          final p = TuyaPayloads(devId, device22: device22);
          final dps = (jsonDecode(v['json']! as String) as Map)['dps'] as Map?;
          final (sendCmd, json) = switch (cmd) {
            TuyaCmd.dpQuery => p.dpQuery(now, dps: [1, 9]),
            TuyaCmd.control => p.control(now, {
              for (final e in dps!.entries) int.parse(e.key as String): e.value,
            }),
            TuyaCmd.heartBeat => p.heartBeat(),
            _ => throw StateError('unexpected'),
          };
          expect(sendCmd, v['sentCommand']);
          expect(json, v['json']);
          final frame = TuyaCodec3x(
            version,
            key,
          ).encode(v['seq']! as int, sendCmd, json);
          expect(toHex(frame), v['frame']);
        },
      );
    }
  });

  group('device frames decode vs tinytuya', () {
    for (final v in (vectors['device']! as List).cast<Map<String, Object?>>()) {
      test('cmd ${v['cmd']} seq ${v['seq']}', () {
        final frames = TuyaFrameDecoder().add(hex(v['frame']! as String));
        expect(frames, hasLength(1));
        final f = frames.single;
        expect(f.crcOk, isTrue);
        expect(f.seq, v['seq']);
        expect(f.cmd, v['cmd']);
        expect(f.retcode, v['retcode']);
        final d = TuyaCodec3x('3.3', key).decode(f.payload);
        expect((d as TuyaJson).json, v['json']);
      });
    }
  });

  test('stream decoder: split, concatenated, garbage-prefixed frames', () {
    final frames = (vectors['device']! as List)
        .cast<Map<String, Object?>>()
        .map((v) => hex(v['frame']! as String))
        .toList();
    final all = [0x13, 0x37, ...frames[0], ...frames[1], ...frames[2]];
    final dec = TuyaFrameDecoder();
    final got = <TuyaFrame>[];
    for (var i = 0; i < all.length; i += 7) {
      got.addAll(
        dec.add(all.sublist(i, i + 7 > all.length ? all.length : i + 7)),
      );
    }
    expect(got.map((f) => f.cmd), [10, 8, 7]);
    expect(got.every((f) => f.crcOk), isTrue);
  });

  test('corrupted byte → crcOk false', () {
    final f = hex(
      ((vectors['device']! as List).first as Map)['frame']! as String,
    );
    f[20] ^= 0xFF;
    expect(TuyaFrameDecoder().add(f).single.crcOk, isFalse);
  });

  test('client frame round-trips through the decoder (sim side)', () {
    final codec = TuyaCodec3x('3.3', key);
    final (cmd, json) = TuyaPayloads('abc').control(now, {1: true});
    final frame = codec.encode(9, cmd, json);
    final f = TuyaFrameDecoder(hasRetcode: false).add(frame).single;
    expect(f.seq, 9);
    expect((codec.decode(f.payload) as TuyaJson).json['dps'], {'1': true});
  });

  test(
    '3.1: control is signed+base64, round-trips; plaintext JSON decodes',
    () {
      final codec = TuyaCodec3x('3.1', key);
      final v = (vectors['client']! as List).cast<Map<String, Object?>>().last;
      final f = TuyaFrameDecoder(hasRetcode: false)
          .add(hex(v['frame']! as String))
          .single;
      expect(ascii.decode(f.payload.sublist(0, 3)), '3.1');
      expect((codec.decode(f.payload) as TuyaJson).json['dps'], {'1': false});
      expect(
        (codec.decode(
          Uint8List.fromList(utf8.encode('{"dps":{"1":true}}')),
        ) as TuyaJson).json,
        {
          'dps': {'1': true},
        },
      );
    },
  );

  test('"data unvalid" → device22 signal; empty → ack', () {
    final codec = TuyaCodec3x('3.3', key);
    final enc = aesEcbEncrypt(codec.key, utf8.encode('json obj data unvalid'));
    expect(codec.decode(enc), isA<TuyaDevice22>());
    expect(codec.decode(Uint8List(0)), isA<TuyaEmpty>());
  });

  test('bad key length / version rejected', () {
    expect(() => TuyaCodec3x('3.3', 'short'), throwsArgumentError);
    expect(() => TuyaCodec3x('3.4', key), throwsArgumentError);
  });

  test(
    'UDP beacon (55AA-framed, encrypted) decodes like tinytuya decrypt_udp',
    () {
      final b = vectors['beacon']! as Map<String, Object?>;
      expect(decodeTuyaBeacon(hex(b['frame6667']! as String)), b['json']);
      expect(
        decodeTuyaBeacon(
          Uint8List.fromList(utf8.encode('{"gwId":"x","ip":"1.2.3.4"}')),
        ),
        {'gwId': 'x', 'ip': '1.2.3.4'},
      );
      expect(decodeTuyaBeacon(Uint8List.fromList([1, 2, 3])), isNull);
    },
  );
}
