import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:offline_home/adapters/tuya/tuya_codec.dart';

import 'tuya_codec_test.dart' show hex, toHex;

/// Vectors generated by tinytuya itself: sim/tools/gen_tuya_vectors.py (v35()).
final v = jsonDecode(
  File('test/adapters/tuya/vectors_35.json').readAsStringSync(),
) as Map<String, Object?>;

void main() {
  final key = v['key']! as String;
  final iv = hex(v['iv']! as String);
  final now = DateTime.fromMillisecondsSinceEpoch((v['t']! as int) * 1000);

  TuyaCodec35 codec([String k = '']) =>
      TuyaCodec35(k.isEmpty ? key : k, iv: () => iv);

  TuyaCodec35 negotiated() {
    final c = codec()..negotiateStart(1, hex(v['localNonce']! as String));
    final resp = TuyaFrameDecoder(hmacKey: c.realKey)
        .add(hex(v['step2']! as String))
        .single;
    c.negotiateFinish(2, resp);
    return c;
  }

  test('6699 session negotiation matches tinytuya byte for byte', () {
    final c = codec();
    expect(
      toHex(c.negotiateStart(1, hex(v['localNonce']! as String))),
      v['step1'],
    );
    final resp = TuyaFrameDecoder(hmacKey: c.realKey)
        .add(hex(v['step2']! as String))
        .single;
    expect(resp.crcOk, isTrue);
    expect(resp.retcode, 0);
    expect(toHex(c.negotiateFinish(2, resp)), v['step3']);
    expect(toHex(c.sessionKey!), v['sessionKey']);
  });

  test('wrong key: GCM tag fails, negotiation refused', () {
    final c = codec('WrongKeyWrongKey')
      ..negotiateStart(1, hex(v['localNonce']! as String));
    final resp = TuyaFrameDecoder(hmacKey: c.realKey)
        .add(hex(v['step2']! as String))
        .single;
    expect(resp.crcOk, isFalse);
    expect(
      () => c.negotiateFinish(2, resp),
      throwsA(isA<TuyaDecodeException>()),
    );
  });

  group('client frames byte-exact', () {
    for (final f in (v['client']! as List).cast<Map<String, Object?>>()) {
      test('cmd 0x${(f['command']! as int).toRadixString(16)}', () {
        final c = negotiated();
        final p = TuyaPayloads(v['devId']! as String, version: '3.5');
        final (cmd, body) = switch (f['command']) {
          TuyaCmd.dpQuery => p.dpQuery(now),
          TuyaCmd.control => p.control(now, {1: true}),
          TuyaCmd.heartBeat => p.heartBeat(),
          _ => throw StateError('unexpected'),
        };
        expect(cmd, f['sentCommand']);
        expect(body, f['json']);
        expect(toHex(c.encode(f['seq']! as int, cmd, body)), f['frame']);
      });
    }
  });

  group('device frames decode like tinytuya', () {
    for (final f in (v['device']! as List).cast<Map<String, Object?>>()) {
      test('cmd 0x${(f['cmd']! as int).toRadixString(16)}', () {
        final c = negotiated();
        final frame = TuyaFrameDecoder(hmacKey: c.frameKey)
            .add(hex(f['frame']! as String))
            .single;
        expect(frame.crcOk, isTrue);
        expect(frame.retcode, 0);
        expect(frame.seq, f['seq']);
        final d = c.decode(frame.payload);
        if (f['decoded'] == null) {
          expect(d, isA<TuyaEmpty>());
        } else {
          expect((d as TuyaJson).json, f['decoded']);
        }
      });
    }
  });

  test('frames split across reads and mixed with 55AA resync', () {
    final c = negotiated();
    final bytes = [
      ...[1, 2, 3], // garbage
      for (final f in (v['device']! as List).cast<Map<String, Object?>>())
        ...hex(f['frame']! as String),
    ];
    final dec = TuyaFrameDecoder(hmacKey: c.frameKey);
    final got = [
      ...dec.add(bytes.sublist(0, 40)),
      ...dec.add(bytes.sublist(40)),
    ];
    expect(got.map((f) => f.cmd), [
      TuyaCmd.dpQueryNew,
      TuyaCmd.status,
      TuyaCmd.controlNew,
    ]);
  });

  test('port-7000 beacon and REQ_DEVINFO match tinytuya', () {
    final b = v['beacon7000']! as Map<String, Object?>;
    expect(decodeTuyaBeacon(hex(b['frame']! as String)), b['json']);
    final r = v['reqDevInfo']! as Map<String, Object?>;
    expect(toHex(tuyaDevInfoRequest(r['ip']! as String, iv: iv)), r['frame']);
    expect(tuyaBeaconPorts, contains(7000));
  });
}
