import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:offline_home/adapters/tuya/tuya_codec.dart';

import 'tuya_codec_test.dart' show hex, toHex;

/// Vectors generated by tinytuya itself: sim/tools/gen_tuya_vectors.py (v34()).
final v = jsonDecode(
  File('test/adapters/tuya/vectors_34.json').readAsStringSync(),
) as Map<String, Object?>;

void main() {
  final key = v['key']! as String;
  final now = DateTime.fromMillisecondsSinceEpoch((v['t']! as int) * 1000);

  TuyaCodec34 negotiated() {
    final c = TuyaCodec34(key);
    c.negotiateStart(1, hex(v['localNonce']! as String));
    final resp = TuyaFrameDecoder(hmacKey: c.realKey)
        .add(hex(v['step2']! as String))
        .single;
    c.negotiateFinish(2, resp);
    return c;
  }

  test('session negotiation matches tinytuya byte for byte', () {
    final c = TuyaCodec34(key);
    expect(
      toHex(c.negotiateStart(1, hex(v['localNonce']! as String))),
      v['step1'],
    );
    expect(c.frameKey, c.realKey);
    final resp = TuyaFrameDecoder(hmacKey: c.realKey)
        .add(hex(v['step2']! as String))
        .single;
    expect(resp.crcOk, isTrue);
    expect(resp.cmd, TuyaCmd.sessKeyNegResp);
    expect(toHex(c.negotiateFinish(2, resp)), v['step3']);
    expect(toHex(c.sessionKey!), v['sessionKey']);
    expect(c.frameKey, c.sessionKey);
  });

  test('wrong local key: HMAC fails, negotiation refused', () {
    final c = TuyaCodec34('WrongKeyWrongKey');
    c.negotiateStart(1, hex(v['localNonce']! as String));
    final resp = TuyaFrameDecoder(hmacKey: c.realKey)
        .add(hex(v['step2']! as String))
        .single;
    expect(resp.crcOk, isFalse);
    expect(
      () => c.negotiateFinish(2, resp),
      throwsA(isA<TuyaDecodeException>()),
    );
  });

  group('client frames byte-exact', () {
    for (final f in (v['client']! as List).cast<Map<String, Object?>>()) {
      test('cmd 0x${(f['command']! as int).toRadixString(16)}', () {
        final c = negotiated();
        final p = TuyaPayloads(v['devId']! as String, version: '3.4');
        final json = jsonDecode(f['json']! as String) as Map;
        final (cmd, body) = switch (f['command']) {
          TuyaCmd.dpQuery => p.dpQuery(now),
          TuyaCmd.control => p.control(now, {
            for (final e in ((json['data'] as Map)['dps'] as Map).entries)
              int.parse(e.key as String): e.value,
          }),
          TuyaCmd.heartBeat => p.heartBeat(),
          _ => throw StateError('unexpected'),
        };
        expect(cmd, f['sentCommand']);
        expect(body, f['json']);
        expect(toHex(c.encode(f['seq']! as int, cmd, body)), f['frame']);
      });
    }
  });

  group('device frames decode like tinytuya', () {
    for (final f in (v['device']! as List).cast<Map<String, Object?>>()) {
      test('cmd 0x${(f['cmd']! as int).toRadixString(16)}', () {
        final c = negotiated();
        final frame = TuyaFrameDecoder(hmacKey: c.frameKey)
            .add(hex(f['frame']! as String))
            .single;
        expect(frame.crcOk, isTrue);
        expect(frame.retcode, 0);
        final d = c.decode(frame.payload);
        if (f['decoded'] == null) {
          expect(d, isA<TuyaEmpty>());
        } else {
          expect((d as TuyaJson).json, f['decoded']);
        }
      });
    }
  });
}
