#!/usr/bin/env python3
"""Generate byte-exact Tuya 3.1/3.3 codec vectors with tinytuya (the reference, CLAUDE.md
rule 2). Output: app/test/adapters/tuya/vectors_3x.json, consumed by the Dart codec tests.

    pip install tinytuya==1.20.0 && python sim/tools/gen_tuya_vectors.py

Frames are produced by tinytuya's own XenonDevice.generate_payload + _encode_message
(tinytuya/core/XenonDevice.py) with time.time() pinned, so they are what a real tinytuya
client sends. Device replies are built with the same crypto and checked by tinytuya's
unpack_message + _decode_payload.
"""

from __future__ import annotations

import binascii
import json
import struct
import time
from hashlib import md5
from pathlib import Path
from unittest import mock

import tinytuya
from tinytuya.core import command_types as CT
from tinytuya.core import header as H
from tinytuya.core import udp_helper
from tinytuya.core.crypto_helper import AESCipher
from tinytuya.core.message_helper import unpack_message

DEV_ID = "bf0123456789abcdefghij"  # 22 chars → also usable for device22 vectors
DEV_ID_20 = "01234567890123456789"
KEY = "0123456789abcdef"
T = 1727600000
OUT = Path(__file__).resolve().parents[2] / "app/test/adapters/tuya/vectors_3x.json"


def client_frame(version: float, dev_id: str, command: int, data=None, seq: int = 1, dev_type: str = "default"):
    d = tinytuya.OutletDevice(dev_id, "127.0.0.1", KEY, version=version)
    if dev_type != "default":
        d.set_dpsUsed({"1": None, "9": None})
        d.dev_type = dev_type
        d.payload_dict = None  # force regeneration for the new dev_type
    d.seqno = seq
    with mock.patch.object(time, "time", return_value=T + 0.4):
        payload = d.generate_payload(command, data)
    frame = d._encode_message(payload)
    return {
        "version": str(version),
        "devId": dev_id,
        "command": command,
        "sentCommand": payload.cmd,
        "seq": seq,
        "json": payload.payload.decode(),
        "frame": frame.hex(),
    }


def device_reply(version: float, cmd: int, seq: int, obj: dict, retcode: int = 0, with_header: bool = True):
    """Device→client 55AA frame: header + retcode + payload + crc + suffix."""
    cipher = AESCipher(KEY.encode())
    body = cipher.encrypt(json.dumps(obj, separators=(",", ":")).encode(), use_base64=False)
    if version >= 3.2 and with_header:
        body = H.PROTOCOL_33_HEADER + body
    payload = struct.pack(">I", retcode) + body
    head = struct.pack(">4I", H.PREFIX_55AA_VALUE, seq, cmd, len(payload) + 8)
    crc = binascii.crc32(head + payload) & 0xFFFFFFFF
    frame = head + payload + struct.pack(">2I", crc, H.SUFFIX_55AA_VALUE)
    # Verify with tinytuya's own decoder.
    msg = unpack_message(frame)
    assert msg.crc_good and msg.retcode == retcode
    d = tinytuya.OutletDevice(DEV_ID_20, "127.0.0.1", KEY, version=version)
    assert d._decode_payload(msg.payload) == obj, d._decode_payload(msg.payload)
    return {"version": str(version), "cmd": cmd, "seq": seq, "retcode": retcode, "json": obj, "frame": frame.hex()}


def main() -> None:
    v = {
        "source": f"tinytuya {tinytuya.__version__} (generated by sim/tools/gen_tuya_vectors.py)",
        "key": KEY,
        "t": T,
        "client": [
            client_frame(3.3, DEV_ID_20, CT.DP_QUERY, seq=1),
            client_frame(3.3, DEV_ID_20, CT.CONTROL, {"1": True}, seq=2),
            client_frame(3.3, DEV_ID_20, CT.CONTROL, {"9": 1200}, seq=3),
            client_frame(3.3, DEV_ID_20, CT.HEART_BEAT, seq=4),
            client_frame(3.3, DEV_ID, CT.DP_QUERY, seq=5, dev_type="device22"),
            client_frame(3.1, DEV_ID_20, CT.DP_QUERY, seq=6),
            client_frame(3.1, DEV_ID_20, CT.CONTROL, {"1": False}, seq=7),
        ],
        "device": [
            device_reply(3.3, CT.DP_QUERY, 1, {"devId": DEV_ID_20, "dps": {"1": True, "9": 0}}),
            device_reply(3.3, CT.STATUS, 0, {"devId": DEV_ID_20, "dps": {"1": False}, "t": T}),
            device_reply(3.3, CT.CONTROL, 2, {"dps": {"1": True}, "t": T}, with_header=False),
        ],
        "beacon": {},
    }
    beacon = {"ip": "192.168.1.30", "gwId": DEV_ID_20, "active": 2, "ability": 0, "mode": 0,
              "encrypt": True, "productKey": "keyabc123", "version": "3.3"}
    raw = json.dumps(beacon, separators=(",", ":")).encode()
    enc = udp_helper.encrypt(raw, udp_helper.udpkey)
    head = struct.pack(">4I", H.PREFIX_55AA_VALUE, 0, CT.UDP_NEW, len(enc) + 4 + 8)
    payload = struct.pack(">I", 0) + enc
    crc = binascii.crc32(head + payload) & 0xFFFFFFFF
    frame = head + payload + struct.pack(">2I", crc, H.SUFFIX_55AA_VALUE)
    assert json.loads(udp_helper.decrypt_udp(frame)) == beacon
    v["beacon"] = {
        "udpKey": udp_helper.udpkey.hex(),
        "udpKeyIsMd5Of": "yGAdlopoPVldABfn",
        "json": beacon,
        "frame6667": frame.hex(),
    }
    assert udp_helper.udpkey == md5(b"yGAdlopoPVldABfn").digest()
    OUT.write_text(json.dumps(v, indent=2) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
