#!/usr/bin/env python3
"""Generate byte-exact Tuya 3.1/3.3/3.4 codec vectors with tinytuya (the reference, CLAUDE.md
rule 2). Output: app/test/adapters/tuya/vectors_3x.json, vectors_34.json and vectors_35.json,
consumed by the Dart codec tests.

    pip install tinytuya==1.20.0 && python sim/tools/gen_tuya_vectors.py

Frames are produced by tinytuya's own XenonDevice.generate_payload + _encode_message
(tinytuya/core/XenonDevice.py) with time.time() pinned, so they are what a real tinytuya
client sends. Device replies are built with the same crypto and checked by tinytuya's
unpack_message + _decode_payload.
"""

from __future__ import annotations

import binascii
import hmac
import json
import struct
import time
from hashlib import md5, sha256
from pathlib import Path
from unittest import mock

import tinytuya
from tinytuya.core import command_types as CT
from tinytuya.core import header as H
from tinytuya.core import udp_helper
from tinytuya.core.crypto_helper import AESCipher
from tinytuya.core.message_helper import TuyaMessage, pack_message, unpack_message

DEV_ID = "bf0123456789abcdefghij"  # 22 chars → also usable for device22 vectors
DEV_ID_20 = "01234567890123456789"
KEY = "0123456789abcdef"
T = 1727600000
OUT = Path(__file__).resolve().parents[2] / "app/test/adapters/tuya/vectors_3x.json"
OUT34 = OUT.with_name("vectors_34.json")
OUT35 = OUT.with_name("vectors_35.json")
IV = b"IVIVIVIVIV12"  # fixed 12-byte GCM IV (tinytuya draws os.urandom(12) per frame)
LOCAL_NONCE = bytes(range(0x30, 0x40))  # fixed "random" client nonce for the vectors
REMOTE_NONCE = bytes(range(0x60, 0x70))


def client_frame(version: float, dev_id: str, command: int, data=None, seq: int = 1, dev_type: str = "default"):
    d = tinytuya.OutletDevice(dev_id, "127.0.0.1", KEY, version=version)
    if dev_type != "default":
        d.set_dpsUsed({"1": None, "9": None})
        d.dev_type = dev_type
        d.payload_dict = None  # force regeneration for the new dev_type
    d.seqno = seq
    with mock.patch.object(time, "time", return_value=T + 0.4):
        payload = d.generate_payload(command, data)
    frame = d._encode_message(payload)
    return {
        "version": str(version),
        "devId": dev_id,
        "command": command,
        "sentCommand": payload.cmd,
        "seq": seq,
        "json": payload.payload.decode(),
        "frame": frame.hex(),
    }


def device_reply(version: float, cmd: int, seq: int, obj: dict, retcode: int = 0, with_header: bool = True):
    """Device→client 55AA frame: header + retcode + payload + crc + suffix."""
    cipher = AESCipher(KEY.encode())
    body = cipher.encrypt(json.dumps(obj, separators=(",", ":")).encode(), use_base64=False)
    if version >= 3.2 and with_header:
        body = H.PROTOCOL_33_HEADER + body
    payload = struct.pack(">I", retcode) + body
    head = struct.pack(">4I", H.PREFIX_55AA_VALUE, seq, cmd, len(payload) + 8)
    crc = binascii.crc32(head + payload) & 0xFFFFFFFF
    frame = head + payload + struct.pack(">2I", crc, H.SUFFIX_55AA_VALUE)
    # Verify with tinytuya's own decoder.
    msg = unpack_message(frame)
    assert msg.crc_good and msg.retcode == retcode
    d = tinytuya.OutletDevice(DEV_ID_20, "127.0.0.1", KEY, version=version)
    assert d._decode_payload(msg.payload) == obj, d._decode_payload(msg.payload)
    return {"version": str(version), "cmd": cmd, "seq": seq, "retcode": retcode, "json": obj, "frame": frame.hex()}


def main() -> None:
    v = {
        "source": f"tinytuya {tinytuya.__version__} (generated by sim/tools/gen_tuya_vectors.py)",
        "key": KEY,
        "t": T,
        "client": [
            client_frame(3.3, DEV_ID_20, CT.DP_QUERY, seq=1),
            client_frame(3.3, DEV_ID_20, CT.CONTROL, {"1": True}, seq=2),
            client_frame(3.3, DEV_ID_20, CT.CONTROL, {"9": 1200}, seq=3),
            client_frame(3.3, DEV_ID_20, CT.HEART_BEAT, seq=4),
            client_frame(3.3, DEV_ID, CT.DP_QUERY, seq=5, dev_type="device22"),
            client_frame(3.1, DEV_ID_20, CT.DP_QUERY, seq=6),
            client_frame(3.1, DEV_ID_20, CT.CONTROL, {"1": False}, seq=7),
        ],
        "device": [
            device_reply(3.3, CT.DP_QUERY, 1, {"devId": DEV_ID_20, "dps": {"1": True, "9": 0}}),
            device_reply(3.3, CT.STATUS, 0, {"devId": DEV_ID_20, "dps": {"1": False}, "t": T}),
            device_reply(3.3, CT.CONTROL, 2, {"dps": {"1": True}, "t": T}, with_header=False),
        ],
        "beacon": {},
    }
    beacon = {"ip": "192.168.1.30", "gwId": DEV_ID_20, "active": 2, "ability": 0, "mode": 0,
              "encrypt": True, "productKey": "keyabc123", "version": "3.3"}
    raw = json.dumps(beacon, separators=(",", ":")).encode()
    enc = udp_helper.encrypt(raw, udp_helper.udpkey)
    head = struct.pack(">4I", H.PREFIX_55AA_VALUE, 0, CT.UDP_NEW, len(enc) + 4 + 8)
    payload = struct.pack(">I", 0) + enc
    crc = binascii.crc32(head + payload) & 0xFFFFFFFF
    frame = head + payload + struct.pack(">2I", crc, H.SUFFIX_55AA_VALUE)
    assert json.loads(udp_helper.decrypt_udp(frame)) == beacon
    v["beacon"] = {
        "udpKey": udp_helper.udpkey.hex(),
        "udpKeyIsMd5Of": "yGAdlopoPVldABfn",
        "json": beacon,
        "frame6667": frame.hex(),
    }
    assert udp_helper.udpkey == md5(b"yGAdlopoPVldABfn").digest()
    OUT.write_text(json.dumps(v, indent=2) + "\n")
    print(f"wrote {OUT}")


def device_frame_hmac(seq: int, cmd: int, body: bytes, key: bytes, retcode: int = 0) -> bytes:
    """Device→client 55AA frame with HMAC-SHA256 (3.4): tinytuya pack_message does not add a
    return code, so it is prepended to the payload like the device does."""
    return pack_message(
        TuyaMessage(seq, cmd, retcode, struct.pack(">I", retcode) + body, 0, True, H.PREFIX_55AA_VALUE, False),
        hmac_key=key,
    )


def v34() -> dict:
    """Session negotiation + frames for protocol 3.4 (XenonDevice._negotiate_session_key*,
    _encode_message, _decode_payload; message_helper.pack_message/unpack_message)."""
    real = KEY.encode()
    d = tinytuya.OutletDevice(DEV_ID_20, "127.0.0.1", KEY, version=3.4)
    d.seqno = 1
    with mock.patch("tinytuya.core.XenonDevice.os.urandom", return_value=LOCAL_NONCE):
        step1 = d._negotiate_session_key_generate_step_1()
    frame1 = d._encode_message(step1)
    resp_plain = REMOTE_NONCE + hmac.new(real, LOCAL_NONCE, sha256).digest()
    frame2 = device_frame_hmac(1, CT.SESS_KEY_NEG_RESP, AESCipher(real).encrypt(resp_plain, use_base64=False), real)
    msg2 = unpack_message(frame2, hmac_key=real)
    assert msg2.crc_good
    step3 = d._negotiate_session_key_generate_step_3(msg2)
    assert step3
    frame3 = d._encode_message(step3)
    d._negotiate_session_key_generate_finalize()
    session = d.local_key
    out = {
        "source": f"tinytuya {tinytuya.__version__} (generated by sim/tools/gen_tuya_vectors.py)",
        "key": KEY,
        "t": T,
        "devId": DEV_ID_20,
        "localNonce": LOCAL_NONCE.hex(),
        "remoteNonce": REMOTE_NONCE.hex(),
        "step1": frame1.hex(),
        "step2": frame2.hex(),
        "step3": frame3.hex(),
        "sessionKey": session.hex(),
        "client": [],
        "device": [],
    }
    for cmd, data in ((CT.DP_QUERY, None), (CT.CONTROL, {"1": True}), (CT.CONTROL, {"9": 1200}), (CT.HEART_BEAT, None)):
        seq = d.seqno
        with mock.patch.object(time, "time", return_value=T + 0.4):
            payload = d.generate_payload(cmd, data)
        frame = d._encode_message(payload)
        out["client"].append(
            {"command": cmd, "sentCommand": payload.cmd, "seq": seq, "json": payload.payload.decode(), "frame": frame.hex()}
        )
    cipher = AESCipher(session)
    for cmd, seq, obj, header in (
        (CT.DP_QUERY_NEW, 5, {"dps": {"1": True, "9": 0}}, False),
        (CT.STATUS, 0, {"protocol": 4, "t": T, "data": {"dps": {"1": False}}}, True),
        (CT.CONTROL_NEW, 6, None, False),
    ):
        raw = b"" if obj is None else json.dumps(obj, separators=(",", ":")).encode()
        if header:
            raw = H.PROTOCOL_34_HEADER + raw
        body = b"" if obj is None else cipher.encrypt(raw, use_base64=False)
        frame = device_frame_hmac(seq, cmd, body, session)
        msg = unpack_message(frame, hmac_key=session)
        assert msg.crc_good and msg.retcode == 0
        decoded = d._decode_payload(msg.payload) if body else None
        if obj is not None:
            expect = dict(obj)
            if "data" in expect:
                expect["dps"] = expect["data"]["dps"]
            assert decoded == expect, decoded
        out["device"].append({"cmd": cmd, "seq": seq, "json": obj, "decoded": decoded, "frame": frame.hex()})
    return out


def _urandom(n: int) -> bytes:
    return LOCAL_NONCE if n == 16 else IV[:n]


def v35() -> dict:
    """Protocol 3.5: 6699 AES-GCM frames, GCM session negotiation (same tinytuya sources as
    v34, plus crypto_helper GCM and udp_helper.decrypt_udp / scanner REQ_DEVINFO)."""
    real = KEY.encode()
    d = tinytuya.OutletDevice(DEV_ID_20, "127.0.0.1", KEY, version=3.5)
    d.seqno = 1
    with mock.patch("os.urandom", side_effect=_urandom):
        step1 = d._negotiate_session_key_generate_step_1()
        frame1 = d._encode_message(step1)
        resp = REMOTE_NONCE + hmac.new(real, LOCAL_NONCE, sha256).digest()
        frame2 = pack_message(TuyaMessage(7, CT.SESS_KEY_NEG_RESP, 0, resp, 0, True, H.PREFIX_6699_VALUE, IV), hmac_key=real)
        msg2 = unpack_message(frame2, hmac_key=real)
        assert msg2.crc_good and msg2.payload == resp
        step3 = d._negotiate_session_key_generate_step_3(msg2)
        assert step3
        frame3 = d._encode_message(step3)
        d._negotiate_session_key_generate_finalize()
        session = d.local_key
        out = {
            "source": f"tinytuya {tinytuya.__version__} (generated by sim/tools/gen_tuya_vectors.py)",
            "key": KEY,
            "t": T,
            "devId": DEV_ID_20,
            "iv": IV.hex(),
            "localNonce": LOCAL_NONCE.hex(),
            "remoteNonce": REMOTE_NONCE.hex(),
            "step1": frame1.hex(),
            "step2": frame2.hex(),
            "step3": frame3.hex(),
            "sessionKey": session.hex(),
            "client": [],
            "device": [],
        }
        for cmd, data in ((CT.DP_QUERY, None), (CT.CONTROL, {"1": True}), (CT.HEART_BEAT, None)):
            seq = d.seqno
            with mock.patch.object(time, "time", return_value=T + 0.4):
                payload = d.generate_payload(cmd, data)
            frame = d._encode_message(payload)
            out["client"].append(
                {"command": cmd, "sentCommand": payload.cmd, "seq": seq, "json": payload.payload.decode(), "frame": frame.hex()}
            )
        for cmd, seq, obj, header in (
            (CT.DP_QUERY_NEW, 20, {"dps": {"1": True, "9": 0}}, False),
            (CT.STATUS, 21, {"protocol": 4, "t": T, "data": {"dps": {"1": False}}}, True),
            (CT.CONTROL_NEW, 22, None, False),
        ):
            raw = b"" if obj is None else json.dumps(obj, separators=(",", ":")).encode()
            if header:
                raw = H.PROTOCOL_35_HEADER + raw
            frame = pack_message(TuyaMessage(seq, cmd, 0, raw, 0, True, H.PREFIX_6699_VALUE, IV), hmac_key=session)
            msg = unpack_message(frame, hmac_key=session)
            assert msg.crc_good and msg.retcode == 0 and msg.payload == raw
            decoded = d._decode_payload(msg.payload) if raw else None
            if obj is not None:
                expect = dict(obj)
                if "data" in expect:
                    expect["dps"] = expect["data"]["dps"]
                assert decoded == expect, decoded
            out["device"].append({"cmd": cmd, "seq": seq, "json": obj, "decoded": decoded, "frame": frame.hex()})
        beacon = {"ip": "192.168.1.35", "gwId": DEV_ID_20, "active": 2, "encrypt": True, "productKey": "keyabc123", "version": "3.5"}
        bframe = pack_message(
            TuyaMessage(0, CT.UDP_NEW, None, json.dumps(beacon, separators=(",", ":")).encode(), 0, True, H.PREFIX_6699_VALUE, IV),
            hmac_key=udp_helper.udpkey,
        )
        assert json.loads(udp_helper.decrypt_udp(bframe)) == beacon
        req = pack_message(
            TuyaMessage(0, CT.REQ_DEVINFO, None, json.dumps({"from": "app", "ip": "192.168.1.5"}).encode(), 0, True, H.PREFIX_6699_VALUE, True),
            hmac_key=udp_helper.udpkey,
        )
    out["beacon7000"] = {"json": beacon, "frame": bframe.hex()}
    out["reqDevInfo"] = {"ip": "192.168.1.5", "frame": req.hex()}
    return out


if __name__ == "__main__":
    main()
    OUT35.write_text(json.dumps(v35(), indent=2) + "\n")
    print(f"wrote {OUT35}")
    OUT34.write_text(json.dumps(v34(), indent=2) + "\n")
    print(f"wrote {OUT34}")
